language: node_js
node_js:
        - "node"
script:
- npm test
- node_modules/.bin/jshint src

before_deploy:
- ./node_modules/.bin/jsdoc src

deploy:
    - provider: pages
    - skip-cleanup: true
    - github-token: $GITHUB_TOKEN
    - keep-history: true
    - local-dir: $TRAVIS_BUILD_DIR+"/out"
    - on:
    - branch: master
